parameters:
       
    ws.limit.create:                    500
    ws.limit.update:                    500
    ws.limit.delete:                    500
    ws.limit.getAll:                    500
    ws.limit.getOne:                    500
        
    ws.code.resMissingFields:           1
    ws.code.errorValidateEntity:        2
    ws.code.respInternalError:          3
    ws.code.resMissingParamEndPoint:    4
    ws.code.notResultQuery:             5
    ws.code.errorTypeFields:            6
    ws.code.actionNotEnabled:           7